In [17]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [19]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [23]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(max_iter=1000)
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7033333333333334
[[76 20  7]
 [25 48 23]
 [ 2 12 87]]
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.60      0.50      0.55        96
           2       0.74      0.86      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.70      0.70      0.70       300

